AddIntellisense("ClearOverriddenSucker", "Function", "Function in ExperienceOrb.", "ClearOverriddenSucker()", "ExperienceOrb", "ExperienceOrb.ClearOverriddenSucker");
AddIntellisense("GetECType", "Function", "Function in ExperienceOrb.", "GetECType()", "ExperienceOrb", "ExperienceOrb.GetECType");
AddIntellisense("GetExperienceOnCurrentLevel", "Function", "Function in ExperienceOrb.", "GetExperienceOnCurrentLevel()", "ExperienceOrb", "ExperienceOrb.GetExperienceOnCurrentLevel");
AddIntellisense("GetNumberOfOrbsOnCurrentLevel", "Function", "Function in ExperienceOrb.", "GetNumberOfOrbsOnCurrentLevel()", "ExperienceOrb", "ExperienceOrb.GetNumberOfOrbsOnCurrentLevel");
AddIntellisense("GetSuckMode", "Function", "Function in ExperienceOrb.", "GetSuckMode()", "ExperienceOrb", "ExperienceOrb.GetSuckMode");
AddIntellisense("SetAsEnabled", "Function", "Function in ExperienceOrb.", "SetAsEnabled()", "ExperienceOrb", "ExperienceOrb.SetAsEnabled");
AddIntellisense("SetBaseExperience", "Function", "Function in ExperienceOrb.", "SetBaseExperience()", "ExperienceOrb", "ExperienceOrb.SetBaseExperience");
AddIntellisense("SetOverriddenSucker", "Function", "Function in ExperienceOrb.", "SetOverriddenSucker()", "ExperienceOrb", "ExperienceOrb.SetOverriddenSucker");
AddIntellisense("SetSuckMode", "Function", "Function in ExperienceOrb.", "SetSuckMode()", "ExperienceOrb", "ExperienceOrb.SetSuckMode");
