AddIntellisense("GetSubTargetIndexByType", "Function", "Function in Targeted.", "GetSubTargetIndexByType()", "Targeted", "Targeted.GetSubTargetIndexByType");
AddIntellisense("IsHenchmanWithinInteractionDistance", "Function", "Function in Targeted.", "IsHenchmanWithinInteractionDistance()", "Targeted", "Targeted.IsHenchmanWithinInteractionDistance");
AddIntellisense("IsHeroWithinInteractionDistance", "Function", "Function in Targeted.", "IsHeroWithinInteractionDistance()", "Targeted", "Targeted.IsHeroWithinInteractionDistance");
AddIntellisense("IsSubTargetAvailable", "Function", "Function in Targeted.", "IsSubTargetAvailable()", "Targeted", "Targeted.IsSubTargetAvailable");
AddIntellisense("IsTargetable", "Function", "Function in Targeted.", "IsTargetable()", "Targeted", "Targeted.IsTargetable");
AddIntellisense("IsTargetedByHero", "Function", "Function in Targeted.", "IsTargetedByHero()", "Targeted", "Targeted.IsTargetedByHero");
AddIntellisense("IsTargetLockedByHero", "Function", "Function in Targeted.", "IsTargetLockedByHero()", "Targeted", "Targeted.IsTargetLockedByHero");
AddIntellisense("SetAsTargetable", "Function", "Function in Targeted.", "SetAsTargetable()", "Targeted", "Targeted.SetAsTargetable");
AddIntellisense("UpdateSimSuggestions", "Function", "Function in Targeted.", "UpdateSimSuggestions()", "Targeted", "Targeted.UpdateSimSuggestions");
